
POST http://localhost:5000/api/room HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0N2U3MzEwLWRiNGItNGRkNS04NTI3LTA2OWUxMDRkMmQ2ZSIsImVtYWlsIjoidGVuZGVyNjc5NTExMUBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTcwNzc1NDQ2NywiZXhwIjoxNzA3ODQwODY3fQ.OrcHKnjCEfGbr-dIqP6HlvecQgAzMelEAeU-g35n0Qs

{
    "name": "test room",
    "description": "test description"
}
###
GET http://localhost:5000/api/room HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0N2U3MzEwLWRiNGItNGRkNS04NTI3LTA2OWUxMDRkMmQ2ZSIsImVtYWlsIjoidGVuZGVyNjc5NTExMUBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTcwNzc1NDQ2NywiZXhwIjoxNzA3ODQwODY3fQ.OrcHKnjCEfGbr-dIqP6HlvecQgAzMelEAeU-g35n0Qs
###
GET http://localhost:5000/api/room/ee4b9f6b-7bab-4eda-9316-fad5d3ede239 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0N2U3MzEwLWRiNGItNGRkNS04NTI3LTA2OWUxMDRkMmQ2ZSIsImVtYWlsIjoidGVuZGVyNjc5NTExMUBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTcwNzc1NDQ2NywiZXhwIjoxNzA3ODQwODY3fQ.OrcHKnjCEfGbr-dIqP6HlvecQgAzMelEAeU-g35n0Qs
###
DELETE  http://localhost:5000/api/room/b1f59309-917f-40b0-b615-0471491f8f7a HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0N2U3MzEwLWRiNGItNGRkNS04NTI3LTA2OWUxMDRkMmQ2ZSIsImVtYWlsIjoidGVuZGVyNjc5NTExMUBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTcwNzc1NDQ2NywiZXhwIjoxNzA3ODQwODY3fQ.OrcHKnjCEfGbr-dIqP6HlvecQgAzMelEAeU-g35n0Qs
###
POST http://localhost:5000/api/room/addUserToRoom HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0N2U3MzEwLWRiNGItNGRkNS04NTI3LTA2OWUxMDRkMmQ2ZSIsImVtYWlsIjoidGVuZGVyNjc5NTExMUBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTcwNzc1NDQ2NywiZXhwIjoxNzA3ODQwODY3fQ.OrcHKnjCEfGbr-dIqP6HlvecQgAzMelEAeU-g35n0Qs

{
    "roomId": "ee4b9f6b-7bab-4eda-9316-fad5d3ede239",
    "userId": "547e7310-db4b-4dd5-8527-069e104d2d6e"
}